lint:
  - "**/*.{js,ts,cjs,mjs}"
  - "**/tsconfig*.json"
  - ".eslint*"
  - "pnpm-lock.yaml"
src:
  - "app/**/!(*.test).{js,ts,mjs,cjs}"
  - "**/tsconfig*.json"
  - "pnpm-lock.yaml"
test:
  - "app/**/*.{js,ts,cjs,mjs}"
  - "**/tsconfig*.json"
  - "pnpm-lock.yaml"
