name: Eslint Aggregate Result
description: A GitHub action which aggregates the result of an eslint run to your PR.

inputs:
  eslint-output-path:
    description: Path to the eslint out file, which is in json format
    required: true

outputs:
  eslint-output:
    description: Stylish ESLint output
  has-errors:
    description: Wether ESLint found any errors
  has-warnings:
    description: Wether ESLint found any warnings
  is-every-error-fixable:
    description: Whether every error is auto-fixable
  is-every-warning-fixable:
    description: Whether every warning is auto-fixable

runs:
  using: node20
  main: dist/index.js
