name: "Check Linked Issues"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  main:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository ⏬
        uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/has-linked-issues.js')
            console.log(await script({github, context}))
