name: Label PR

on:
  pull_request:
    types:
      - opened
    branches:
      - master
      - 2.x

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: PR target
        run: echo ${{toJson(github.event.pull_request.base) }}

      - name: PR Number
        run: echo ${{github.event.pull_request.number}}
