name: "Semantic PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Failure handling
      - name: Create message for failure
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        id: message
        uses: Lehoczky/render-nunjucks-template-action@v1.0.0
        with:
          template-path: .github/templates/failed-semantic-pr.md
          vars: |
            {
              "errorMessage": ${{ toJson(steps.lint_pr_title.outputs.error_message) }}
            }
          auto-escape: false
          trim-blocks: true

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: ${{ steps.message.outputs.result }}

      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
